package com.homedesign.android.domain.catalog

private fun e(
    id: String,
    name: String,
    category: String,
    width: Double,
    depth: Double,
    height: Double,
    icon: String? = null,
    doorOrWindow: Boolean = false,
): CatalogEntry = CatalogEntry(
    id = id,
    catalog = "generic",
    name = name,
    category = category,
    width = width,
    depth = depth,
    height = height,
    movable = true,
    doorOrWindow = doorOrWindow,
    icon = icon,
)

val CATALOG_ENTRIES: List<CatalogEntry> = listOf(
    e("Blend Swap CC-0#bed1", "Bed", "Bedroom", 140.7, 208.0, 95.5, icon = "svg/bed.svg"),
    e("Blend Swap CC-0#bedsideTable2", "Bedside table", "Bedroom", 48.55, 48.1, 45.4),
    e("Geantick#dresser", "Dresser", "Bedroom", 138.5, 45.5, 62.0),
    e(
        "Blend Swap CC-0#wardrobeWithSlidingDoors",
        "Wardrobe",
        "Bedroom",
        200.0,
        66.0,
        236.4,
        icon = "svg/wardrobe.svg",
    ),
    e("Blend Swap CC-0#sofa2", "Sofa", "Seating", 166.9, 74.7, 84.8, icon = "svg/sofa.svg"),
    e(
        "Blend Swap CC-0#L_shaped_sofa",
        "Corner sofa",
        "Seating",
        233.7,
        143.6,
        80.0,
        icon = "svg/sofa_l.svg",
    ),
    e("Blend Swap CC-0#armchair2", "Armchair", "Seating", 95.3, 83.3, 78.3, icon = "svg/armchair.svg"),
    e("Blend Swap CC-0#chair", "Chair", "Seating", 51.3, 53.1, 80.0, icon = "svg/chair.svg"),
    e("Blend Swap CC-0#stool2", "Stool", "Seating", 36.1, 36.1, 78.0, icon = "svg/stool.svg"),
    e("Blend Swap CC-0#table", "Dining table", "Tables", 235.0, 100.0, 73.9, icon = "svg/table.svg"),
    e("Blend Swap CC-0#lbDesk", "Desk", "Tables", 160.0, 80.0, 72.3, icon = "svg/desk.svg"),
    e("Omari#frigorifero", "Fridge", "Kitchen", 60.0, 72.5, 218.2),
    e("Blend Swap CC-BY#kitchenSink", "Sink", "Kitchen", 97.6, 61.6, 97.6, icon = "svg/sink.svg"),
    e("Blend Swap CC-0#refrigerator", "Refrigerator", "Kitchen", 90.0, 95.9, 172.3),
    e("Blend Swap CC-0#toiletsUnit", "Toilet", "Bath", 35.3, 69.2, 77.2, icon = "svg/toilet.svg"),
    e("Blend Swap CC-BY#bath_jay_hardy", "Bathtub", "Bath", 180.1, 70.1, 65.1, icon = "svg/bath.svg"),
    e(
        "Blend Swap CC-0#showerStall",
        "Shower stall",
        "Bath",
        93.06,
        111.89,
        200.02,
        icon = "svg/shower.svg",
    ),
    e("Blend Swap CC-0#washbasin", "Washbasin", "Bath", 56.4, 45.7, 93.1),
    e("Blend Swap CC-0#bookcase", "Bookcase", "Storage", 91.9, 36.5, 147.2, icon = "svg/bookcase.svg"),
    e(
        "Blend Swap CC-BY#wardrobe",
        "Wardrobe (narrow)",
        "Storage",
        92.1,
        68.0,
        200.0,
        icon = "svg/wardrobe.svg",
    ),
    e("GdB#lampeHalogene", "Floor lamp", "Lighting", 31.3, 68.9, 180.0),
    e("Blend Swap CC-0#lamp2", "Lamp", "Lighting", 53.4, 51.3, 63.4),
    e("Sheep#lustreBoule", "Pendant light", "Lighting", 30.0, 30.0, 67.6),
    e("Kator Legaz#oriental-rug", "Oriental rug", "Decor", 185.8, 257.7, 2.5),
    e(
        "Blend Swap CC-0#decorativePlant",
        "Decorative plant",
        "Decor",
        55.9,
        60.2,
        103.1,
        icon = "svg/plant.svg",
    ),
    e("Puybaret#rectangularMirror", "Rectangular mirror", "Decor", 50.0, 1.0, 70.0),
    e("Blend Swap CC-0#led_tv", "TV", "Decor", 77.5, 14.2, 50.8),
    e(
        "Scopia#door",
        "Door",
        "Doors and windows",
        96.0,
        17.5,
        210.0,
        icon = "svg/door.svg",
        doorOrWindow = true,
    ),
    e(
        "OlaKristianHoff#window_double_2x3_frame_sill",
        "Double small window 2x3 panes with sill",
        "Doors and windows",
        123.0,
        25.0,
        110.0,
        icon = "svg/window.svg",
        doorOrWindow = true,
    ),
    e(
        "SeberRider#doubleFrenchWindow2",
        "Double French window",
        "Doors and windows",
        150.0,
        25.0,
        221.0,
        icon = "svg/window.svg",
        doorOrWindow = true,
    ),
)

val FURNITURE_CATEGORIES = listOf(
    "Bedroom",
    "Seating",
    "Tables",
    "Kitchen",
    "Bath",
    "Storage",
    "Lighting",
    "Decor",
)

fun catalogById(id: String): CatalogEntry? = CATALOG_ENTRIES.find { it.id == id }
